# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ButtonLayout' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ButtonLayout
pod 'PageMenu', :git => 'https://github.com/orazz/PageMenu.git'
pod 'SnapKit'


pod 'TwicketSegmentedControl'
end
